### ISSUE TITLE
Typo for Loading Image

### ISSUE THREAD

**Issue by TheHollidayInn** [PortalNetwork/nifty-game#58]
The image here misspells "loading" as "loding": https://github.com/PortalNetwork/nifty-game/blob/develop/dapp/src/images/loading.png

I'd submit a PR, but I'm not sure which font. 

Also, the project is awesome, btw :D

**Comment by seanchuangportal** [comment]
Thank you. We will fix it ASAP :)

**Comment by seanchuangportal** [comment]
Loading img change #59 . Close this issue
